[package]
name = "aoc_2020"
version = "0.1.0"
authors = ["rbenua"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
string-error = "0.1.0"
lazy_static = "1.4.0"
